services:
  web:
    build: .
    # REMOVED: ports section - no host port binding for tests
    environment:
      - FLASK_CONFIG=testing
      - FLASK_APP=run.py
      - TEST_DATABASE_URL=mysql+pymysql://testuser:testpass@db:3306/testdb
      - DATABASE_URL=mysql+pymysql://testuser:testpass@db:3306/testdb
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network
    # Health check using Python's built-in urllib (no requests dependency)
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
    # REMOVED: ports section - no host port binding for tests
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    # Fixed health check with proper timing
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "testuser", "-ptestpass"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge