services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_CONFIG=testing
      - FLASK_APP=run.py
      - TEST_DATABASE_URL=mysql+pymysql://testuser:testpass@db:3306/testdb
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
    # ports:
    #   - "3307:3306"  # CHANGE THIS LINE: Map to port 3307 on host instead of 3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "testuser", "-ptestpass"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge